/* Generated by Together */

package owl;

public class AnnotationByEntity extends Annotation {
    /**
     * @supplierCardinality 1
     * @clientRole annotationValue
     * @directed
     */
    public OWLEntity annotationValue;
}
