/* Generated by Together */

package owl;

public class AnnotationByConstant extends Annotation {
    /**
     * @supplierCardinality 1
     * @supplierRole annotationValue
     * @directed
     */
    public Constant annotationValue;
}
