/* Generated by Together */

package owl;

public class AnnotationByAnonymousIndividual extends Annotation {
    /**
     * @supplierCardinality 1
     * @supplierRole annotationValue
     * @directed
     */
    AnonymousIndividual annotationValue;
}
