/* Generated by Together */

package owl;

public class Annotation {
    /**
     * @directed
     * @associates <{Annotation}>
     * @supplierCardinality *
     * @supplierRole annotationAnnotations
     */
    Set annotationAnnotations;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole annotationProperty
     */
    AnnotationProperty annotationProperty;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole annotationValue
     */
    AnnotationValue annotationValue;
}
