/* Generated by Together */

package owl;

public class AnnotationByEntity extends Annotation {
    /**
     * @supplierCardinality 1
     * @supplierRole annotationValue
     * @directed
     */
    OWLEntity annotationValue;
}
