/* Generated by Together */

package owl;

public class Annotation {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole annotationProperty
     */
    AnnotationProperty annotationProperty;
}
