/* Generated by Together */

package owl;

public class ClassAssertion extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole description
     * @directed
     */
    /*#Description description;*/
    /**
     * @supplierCardinality 1
     * @clientRole individual
     * @directed
     */
    /*#Individual individual;*/
}
