/* Generated by Together */

package owl;

public class Constant {
    /**
     * @directed
     * @supplierCardinality 1
     * @alias lexicalValue : String
     */
     public String lexicalValue;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole datatype
     */
    Datatype datatype;
}