/* Generated by Together */

package owl;

public abstract class Constant {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierQualifier value
     */
     String value;
}
