/* Generated by Together */

package owl;

public class DataSomeValuesFrom extends Description {
    /**
     * @supplierCardinality 1
     * @clientRole dataRange
     * @directed
     */
    /*#DataRange dataRange;*/
    /**
     * @link aggregation
     * @associates <{DataPropertyExpression}>
     * @associationAsClass <<list>>
     * @supplierCardinality 1 ..*
     * @clientRole dataProperty
     * @directed
     */
    public List dataProperties;
}
