/* Generated by Together */

package owl;

public class DataMaxCardinality extends Description {
    /**
     * @alias cardinality : int
     */
    public int cardinality;
    /**
     * @directed
     * @supplierCardinality 0..1
     * @supplierRole dataRange
     */
    DataRange datarange;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole dataProperty
     */
    DataPropertyExpression dataProperty;
}
