/* Generated by Together */

package owl;

public class DataComplementOf extends DataRange {
    /**
     * @supplierCardinality 1
     * @clientRole dataRange
     * @directed
     */
    /*#DataRange dataRange;*/
}
