/* Generated by Together */

package owl;

import java.util.*;

public class DataOneOf extends DataRange {
    /**
     * @directed
     * @associates <{Constant}>
     * @supplierCardinality 1 ..*
     * @supplierRole constants
     */
	Set constants;
}
