/* Generated by Together */

package owl;

public class DataPropertyRange extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole dataProperty
     * @directed
     */
    /*#DataPropertyExpression dataProperty;*/
    /**
     * @supplierCardinality 1
     * @clientRole range
     * @directed
     */
    /*#DataRange range;*/
}
