/* Generated by Together */

package owl;

public class DatatypeDefinition extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole datatype
     */
    Datatype datatype;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole dataRange
     */
    DataRange dataRange;
}
