/* Generated by Together */

package owl;

import java.util.*;

public class DataOneOf extends DataRange {
    /**
     * @directed
     * @associates <{owl.Literal}>
     * @supplierCardinality 1 ..*
     * @supplierRole literals
     */
	Set literals;
}
