/* Generated by Together */

package owl;

public class DatatypeRestriction extends DataRange {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole datatype
     */
    Datatype datatype;
    /**
     * @directed
     * @associates <{FacetRestriction}>
     * @supplierCardinality 1..*
     * @supplierRole restrictions
     */
    Set restrictions;
}
