/* Generated by Together */

package owl;

public class DataHasValue extends Description {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole constant
     */
    Constant constant;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole dataProperty
     */
    DataPropertyExpression dataProperty;
}
