/* Generated by Together */

package owl;

public class DataExactCardinality extends Description {
    int cardinality;
    /**
     * @supplierCardinality 0..1
     * @clientRole dataRange
     * @directed
     */
    /*#DataRange dataRange;*/
    /**
     * @supplierCardinality 1
     * @clientRole dataProperty
     * @directed
     */
    /*#DataPropertyExpression dataProperty;*/
}
