/* Generated by Together */

package owl;

public class Declaration extends Axiom {
    /**
     * @supplierCardinality 1
     * @supplierRole entity
     * @directed
     */
    OWLEntity entity;
}
