/* Generated by Together */

package owl;

import java.util.*;

public class DisjointUnion extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole class
     */
    OWLClass _class;
    /**
     * @directed
     * @associates <{Description}>
     * @supplierCardinality 2 ..*
     * @supplierRole classes
     */
    Set disjointClasses;
}
