/* Generated by Together */

package owl;

import java.util.*;

public class DisjointDataProperties extends Axiom {
    /**
     * @directed
     * @associates <{DataPropertyExpression}>
     * @supplierCardinality 2 ..*
     * @supplierRole dataPropertyExpressions
     */
    Set dataPropertyExpressions;
}
