/* Generated by Together */

package owl;

import java.util.*;

public class DisjointUnion extends ClassAxiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole class
     */
    Class _class;
    /**
     * @directed
     * @associates <{owl.ClassExpression}>
     * @supplierCardinality 2 ..*
     * @supplierRole disjointClassExpressions
     */
    Set disjointClassExpressions;
}
