/* Generated by Together */

package owl;

public abstract class Entity {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole entityIRI
     */
    IRI entityIRI;
}


