/* Generated by Together */

package owl;

public abstract class Entity {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole entityURI
     */
    URI entityURI;
}


