/* Generated by Together */

package owl;

public class EntityAnnotation extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole entity
     * @directed
     */
    /*#OWLEntity entity;*/
    /**
     * @link aggregation
     * @associates <{Annotation}>
     * @associationAsClass <<set>>
     * @supplierCardinality 1 ..  *
     * @clientRole entityAnnotations
     * @directed
     */
    public Set entityAnnotations;
}