/* Generated by Together */

package owl;

public class EntityAnnotation extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole entity
     */
    Entity entity;
    /**
     * @directed
     * @associates <{Annotation}>
     * @supplierCardinality 1 ..  *
     * @supplierRole entityAnnotations
     */
    Set entityAnnotations;
}