/* Generated by Together */

package owl;

import java.util.*;

public class EquivalentClasses extends Axiom {
    /**
     * @directed
     * @associates <{Description}>
     * @supplierCardinality 2 ..*
     * @supplierRole classes
     */
    Set classes;
}
