/* Generated by Together */

package owl;

import java.util.*;

public class EquivalentClasses extends Axiom {

    /**
     * @link aggregation
     * @associates <{Description}>
     * @associationAsClass <<set>>
     * @supplierCardinality 2 ..*
     * @clientRole classes
     * @directed
     */
    public Set classes;
}
