/* Generated by Together */

package owl;

public class FacetConstantPair {
    /**
     * @alias facet : String
     */
    public String facet;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole constant
     */
    Constant constant;
}
