/* Generated by Together */

package owl;

public class FacetRestriction {
    /**
     * @alias cinstrainingFacet : String
     */
    public String cinstrainingFacet;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole restrictionValue
     */
    Literal restrictionValue;
}
