/* Generated by Together */

package owl;

public class FacetRestriction {
    /**
     * @alias facet : String
     */
    public String facet;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole literal
     */
    Literal literal;
}
