/* Generated by Together */

package owl;

public class FunctionalDataProperty extends DataPropertyAxiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole dataPropertyExpression
     */
    DataPropertyExpression dataPropertyExpression;
}
