/* Generated by Together */

package owl;

public class InverseObjectProperty extends ObjectPropertyExpression {
    /**
     * @supplierCardinality 1
     * @supplierRole objectProperty
     * @directed
     */
    ObjectPropertyExpression objectProperty;
}
