/* Generated by Together */

package owl;

public class InverseObjectProperties extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole objectProperty1
     */
    ObjectPropertyExpression objectProperty1;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole objectProperty2
     */
    ObjectPropertyExpression objectProperty2;
}
