/* Generated by Together */

package owl;

public class InverseObjectProperties extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole objectPropertyExpression1
     */
    ObjectPropertyExpression objectPropertyExpression1;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole objectPropertyExpression2
     */
    ObjectPropertyExpression objectPropertyExpression2;
}
