/* Generated by Together */

package owl;

public class InverseObjectProperty extends ObjectPropertyExpression {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole objectProperty
     */
    ObjectProperty objectProperty;
}
