/* Generated by Together */

package owl;

public class KeyFor extends Axiom {
    /**
     * @directed
     * @associates <{owl.ObjectPropertyExpression}>
     * @supplierCardinality 0 .. *
     * @supplierRole objectPropertyExpressions
     */
    Set objectPropertyExpressions;
    /**
     * @directed
     * @associates <{owl.DataPropertyExpression}>
     * @supplierCardinality 0 .. *
     * @supplierRole dataPropertyExpressions
     */
    Set dataPropertyExpressions;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole classExpression
     */
    ClassExpression classExpression;
}
