/* Generated by Together */

package owl;

public class NegativeObjectPropertyAssertion extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole objectProperty
     */
    ObjectPropertyExpression objectProperty;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole sourceIndividual
     */
    Individual sourceIndividual;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole targetIndividual
     */
    Individual targetIndividual;
}
