/* Generated by Together */

package owl;

public class NegativeDataPropertyAssertion extends Assertion {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole dataPropertyExpression
     */
    DataPropertyExpression dataPropertyExpression;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole sourceIndividual
     */
    Individual sourceIndividual;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole targetValue
     */
    Literal targetValue;
}
