/* Generated by Together */

package owl;

public class NegativeObjectPropertyAssertion extends Assertion {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole objectPropertyExpression
     */
    ObjectPropertyExpression objectPropertyExpression;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole sourceIndividual
     */
    Individual sourceIndividual;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole targetIndividual
     */
    Individual targetIndividual;
}
