/* Generated by Together */

package owl;

public class NegativeDataPropertyAssertion extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole dataProperty
     * @directed
     */
    /*#DataPropertyExpression dataProperty*/
    /**
     * @supplierCardinality 1
     * @clientRole sourceIndividual
     * @directed
     */
    /*#Individual sourceIndividual;*/
    /**
     * @supplierCardinality 1
     * @clientRole targetValue
     * @directed
     */
    /*#Constant targetValue;*/
}
