/* Generated by Together */

package owl;

public class ObjectUnionOf extends ClassExpression {
    /**
     * @associates <{owl.ClassExpression}>
     * @supplierCardinality 2 .. *
     * @supplierRole classExpressions
     * @directed
     */
    Set classExpressions;
}
