/* Generated by Together */

package owl;

public class ObjectComplementOf extends ClassExpression {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole classExpression
     */
    ClassExpression classExpression;
}
