/* Generated by Together */

package owl;

public class ObjectUnionOf extends Description {
    /**
     * @link aggregation
     * @associates <{Description}>
     * @associationAsClass <<set>>
     * @supplierCardinality 2 .. *
     * @clientRole classes
     * @directed
     */
    public Set classes;
}
