/* Generated by Together */

package owl;

public class ObjectPropertyRange extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole objectPropertyExpression
     */
    ObjectPropertyExpression objectPropertyExpression;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole range
     */
    ClassExpression range;
}
