/* Generated by Together */

package owl;

public class ObjectAllValuesFrom extends Description {
    /**
     * @supplierCardinality 1
     * @clientRole class
     * @directed
     */
    /*#Description _class;*/
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty
     * @directed
     */
    /*#ObjectPropertyExpression objectProperty;*/
}
