/* Generated by Together */

package owl;

import java.util.*;

public class ObjectIntersectionOf extends Description {

    /**
     * @associates <{Description}>
     * @supplierCardinality 2 ..*
     * @supplierRole classes
     * @directed
     */
    public Set classes;
}
