/* Generated by Together */

package owl;

public class ObjectOneOf extends Description {

    /**
     * @link aggregation
     * @associates <{Individual}>
     * @associationAsClass <<set>>
     * @supplierCardinality 1 ..*
     * @clientRole individuals
     * @directed
     */
	public Set individuals;
}
