/* Generated by Together */

package owl;

public class ObjectSomeValuesFrom extends Description {
    /**
     * @supplierCardinality 1
     * @supplierRole class
     * @directed
     */
    Description _class;
    /**
     * @supplierCardinality 1
     * @supplierRole objectProperty
     * @directed
     */
    ObjectPropertyExpression objectProperty;
}
