/* Generated by Together */

package owl;

public class ObjectPropertyDomain extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole objectProperty
     */
    ObjectPropertyExpression objectProperty;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole domain
     */
    Description domain;
}
