/* Generated by Together */

package owl;

public class ObjectHasValue extends ClassExpression {
    /**
     * @supplierCardinality 1
     * @supplierRole individual
     * @directed
     */
    Individual individual;
    /**
     * @supplierCardinality 1
     * @supplierRole objectPropertyExpression
     * @directed
     */
    ObjectPropertyExpression objectPropertyExpression;
}
