/* Generated by Together */

package owl;

public class ObjectHasValue extends Description {
    /**
     * @supplierCardinality 1
     * @clientRole individual
     * @directed
     */
    /*#Individual individual;*/
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty
     * @directed
     */
    /*#ObjectPropertyExpression objectProperty;*/
}
