/* Generated by Together */

package owl;

public class ObjectOneOf extends ClassExpression {

    /**
     * @associates <{Individual}>
     * @supplierCardinality 1 ..*
     * @supplierRole individuals
     * @directed
     */
	public Set individuals;
}
