/* Generated by Together */

package owl;

public class ReflexiveObjectProperty extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole objectPropertyExpression
     */
    ObjectPropertyExpression objectPropertyExpression;
}
