/* Generated by Together */

package owl;

import java.util.*;

public class SameIndividual extends Assertion {
    /**
     * @directed
     * @associates <{Individual}>
     * @supplierCardinality 2 ..*
     * @supplierRole individuals
     */
    Set individuals;
}
