/* Generated by Together */

package owl;

import java.util.*;

public class SameIndividual extends Axiom {

    /**
     * @link aggregation
     * @associates <{Individual}>
     * @associationAsClass <<set>>
     * @supplierCardinality 2 ..*
     * @clientRole individuals
     * @directed
     */
    public Set individuals;
}
