/* Generated by Together */

package owl;

import java.util.*;

public class SubDataPropertyOf extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole subDataProperty
     * @directed
     */
    /*#DataPropertyExpression subDataProperty;*/
    /**
     * @supplierCardinality 1
     * @clientRole superDataProperty
     * @directed
     */
    /*#DataPropertyExpression superdataProperty;*/
}
