/* Generated by Together */

package owl;

import java.util.*;

public class SubDataPropertyOf extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole subDataPropertyExpression
     */
    DataPropertyExpression subDataPropertyExpression;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole superDataPropertyExpression
     */
    DataPropertyExpression superdataPropertyExpression;
}
