/* Generated by Together */

package owl;

import java.util.*;

public class SubObjectPropertyOf extends Axiom {
    /**
     * @link aggregation
     * @associates <{ObjectPropertyExpression}>
     * @associationAsClass <<list>>
     * @supplierCardinality 1 ..*
     * @clientRole subObjectProperties
     * @directed
     */
    public List subObjectProperties;
    /**
     * @supplierCardinality 1
     * @clientRole superObjectProperty
     * @directed
     */
    /*#ObjectPropertyExpression superObjectProperty;*/
}
