/* Generated by Together */

package owl;

public class TransitiveObjectProperty extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole objectProperty
     */
    ObjectPropertyExpression objectProperty;
}
