/* Generated by Together */

package owl;

public class TypedConstant extends Constant {
    /**
     * @supplierCardinality 1
     * @directed
     * @link aggregation
     * @clientRole datatypeURI 
     */
    public URI datatypeURI;
}
