/* Generated by Together */

package owl;

public class TypedConstant extends Constant {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole datatypeURI
     */
    URI datatypeURI;
}
