/* Generated by Together */

package owl;

public class URIAnnotation extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole uri
     */
    URI uri;
    /**
     * @directed
     * @associates <{Annotation}>
     * @supplierCardinality 1 ..  *
     * @supplierRole uriAnnotations
     */
    Set uriAnnotations;
}