/* Generated by Together */

package dig;

import java.util.*;

import owl.*;

public class AreObjectPropertiesDisjoint extends RequestToOntology {
    /**
     * @link aggregation
     * @associates <{ObjectPropertyExpression}>
     * @associationAsClass <<set>>
     * @supplierCardinality 2 ..*
     * @clientRole objectProperties
     * @directed
     */
    public Set objectProperties;
}
