/* Generated by Together */

package dig;

import owl.*;

public class GetClassInstances extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole class
     * @directed
     */
    public Description _class;
}
