/* Generated by Together */

package dig;

import owl.*;

public class GetClassHierarchyNodeByClass extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole class
     * @directed*/
    public Class _class;
}
