/* Generated by Together */

package dig;

import owl.*;

public class GetClassHierarchyNodeByID extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole nodeID
     * @directed*/
    public String nodeID;
}
