/* Generated by Together */

package dig;

import owl.*;

public class GetObjectPropertiesBetween extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole sourceIndividual
     * @directed
     */
    public Individual sourceIndividual;
    /**
     * @supplierCardinality 1
     * @clientRole targetIndividual
     * @directed
     */
    public Individual targetIndividual;
}
