/* Generated by Together */

package dig;

import owl.*;

public class IsObjectPropertyXXX extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty
     * @directed
     */
    public ObjectPropertyExpression objectProperty;
}
