/* Generated by Together */

package dig;

import owl.*;

public class ObjectPropertyFiller {
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty
     * @directed
     */
	public ObjectProperty objectProperty;
    /**
     * @supplierCardinality 1
     * @clientRole value
     * @directed
     */
    public Individual value;
}
