/* Generated by Together */

package dig;

public class OneObjectPropertyHierarchyNode extends Response {
    /**
     * @link aggregationByValue
     * @directed 
     */
    public ObjectPropertyHierarchyNode node;
}
