/* Generated by Together */

package dig;

import java.util.*;

public class RequestMessage {
    /**
     * @link aggregationByValue
     * @associates <{dig.Request}>
     * @associationAsClass <<list>>
     * @supplierCardinality 1 ..*
     * @clientRole requests
     * @directed
     */
    public List requests;
}
