/* Generated by Together */

package dig;

public class SetOfObjectPropertyHierarchyNodes extends Response {
    /**
     * @link aggregationByValue
     * @associates <{ObjectPropertyHierarchyNode}>
     * @associationAsClass <<set>>
     * @supplierCardinality 0..*
     * @clientRole nodes
     * @directed
     */
    public Set nodes;
}
