/* Generated by Together */

package dig;

import java.util.*;

import owl.*;

public class SetOfAnnotations extends Response {
    /**
     * @link aggregationByValue
     * @associates <{Annotation}>
     * @associationAsClass <<set>>
     * @supplierCardinality 0..*
     * @clientRole annotations
     * @directed
     */
    public SetOfEntites annotations;
}
