/* Generated by Together */

package dig;

import java.util.*;

public class SetOfImports extends Response {
    /**
     * @link aggregationByValue
     * @associates <{dig.Imports}>
     * @associationAsClass <<set>>
     * @supplierCardinality 0..*
     * @clientRole imports
     * @directed
     */
    public Set importedOntologies;
}
