/* Generated by Together */

package dig;

import java.util.*;

import owl.*;

public class AreClassesDisjoint extends RequestToOntology {
    /**
     * @link aggregation
     * @associates <{Description}>
     * @associationAsClass <<set>>
     * @supplierCardinality 2 ..*
     * @clientRole classes
     * @directed
     */
    public Set classes;
}
