/* Generated by Together */

package dig;

import java.util.*;

import owl.*;

public class ClassHierarchyNode {
    public String nodeID;
    /**
     * @link aggregationByValue
     * @associates <{owl.Class}>
     * @associationAsClass <<set>>
     * @supplierCardinality 1..*
     * @clientRole equivalentClasses
     * @directed
     */
    public Set equivalentClasses;
    public Set superNodeIDs;
    public Set subNodeIDs;
}
