/* Generated by Together */

package dig;

import owl.*;

public class DataPropertyFiller {
    /**
     * @supplierCardinality 1
     * @clientRole dataProperty
     * @directed
     */
	public DataProperty dataProperty;
    /**
     * @supplierCardinality 1
     * @clientRole value
     * @directed
     */
    public Constant value;
}
