/* Generated by Together */

package dig;

import owl.*;

public class GetChildClassHierarchyNodes extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole class
     * @directed
     */
    public OWLClass _class;
    public boolean onlyDirectNodes;
}
