/* Generated by Together */

package dig;

import owl.*;

public class GetDataPropertiesBetween extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole sourceIndividual
     * @directed
     */
    public Individual sourceIndividual;
    /**
     * @supplierCardinality 1
     * @clientRole targetConstant
     * @directed
     */
    public Literal targetConstant;
}
