/* Generated by Together */

package dig;

import owl.*;

public class GetIndividualTypes extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole individual
     * @directed
     */
    public Individual individual;
    public boolean onlyDirectNodes;
}
