/* Generated by Together */

package dig;

import owl.*;

public class GetIndividualFillers extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole individual
     * @directed
     */
    public Individual individual;
}
