/* Generated by Together */

package dig;

import owl.*;

public class GetObjectPropertyHieararchyNodeByObjectProperty extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty
     * @directed
     */
    public ObjectProperty objectProperty;
}
