/* Generated by Together */

package dig;

import owl.*;

public class GetParentObjectPropertyHierarchyNodes extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty
     * @directed
     */
    public ObjectProperty objectProperty;
    public boolean onlyDirectNodes;
}
