/* Generated by Together */

package dig;

import java.util.*;

import owl.*;

public class IndividualFillers extends Response {
    /**
     * @associates <{ObjectPropertyFiller}>
     * @associationAsClass <<set>>
     * @supplierCardinality 0..*
     * @clientRole objectPropertyFillers
     * @directed
     * @link aggregationByValue
     */
    public Set objectPropertyFillers;
    /**
     * @associates <{DataPropertyFiller}>
     * @associationAsClass <<set>>
     * @supplierCardinality 0..*
     * @clientRole dataPropertyFillers
     * @directed
     * @link aggregationByValue
     */
    public Set dataPropertyFillers;
}
