/* Generated by Together */

package dig;

import owl.*;

public class IsClassSubsumedBy extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole subClass
     * @directed
     */
    public ClassExpression subClass;
    /**
     * @supplierCardinality 1
     * @clientRole superClass
     * @directed
     */
    public ClassExpression superClass;
}
