/* Generated by Together */

package dig;

import owl.*;

public class IsClassSatisfiable extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole class
     * @directed
     */
    public ClassExpression _class;
}
