/* Generated by Together */

package dig;

import owl.*;

public class IsClassSubsumedBy extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole subClass
     * @directed
     */
    public Description subClass;
    /**
     * @supplierCardinality 1
     * @clientRole superClass
     * @directed
     */
    public Description superClass;
}
