/* Generated by Together */

package dig;

import owl.*;

public class IsObjectPropertySubsumedBy extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole subObjectProperty
     * @directed
     */
    public ObjectPropertyExpression subObjectProperty;
    /**
     * @supplierCardinality 1
     * @clientRole superObjectProperty
     * @directed
     */
    public ObjectPropertyExpression superObjectProperty;
}
