/* Generated by Together */

package dig;

import java.util.*;

import owl.*;

public class IsObjectPropertyTransitive extends RequestToOntology {
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty
     * @directed
     */
    public ObjectPropertyExpression objectProperty;
}
