/* Generated by Together */

package dig;

import owl.*;

public class ObjectPropertyHierarchyNode {
    public String nodeID;
    public String nodeID;
    /**
     * @link aggregationByValue
     * @associates <{ObjectProperty}>
     * @associationAsClass <<set>>
     * @supplierCardinality 1..*
     * @clientRole equivalentObjectProperties
     * @directed
     */
    public Set equivalentObjectProperties;
    public Set superNodeIDs;
    public Set subNodeIDs;

}
