/* Generated by Together */

package dig;

public class OneClassHierarchyNode extends Response {
    /**
     * @link aggregationByValue
     * @directed 
     */
    public ClassHierarchyNode node;
}
