/* Generated by Together */

package dig;

public class ResponseMessage {
    /**
     * @link aggregationByValue
     * @associates <{dig.Response}>
     * @associationAsClass <<list>>
     * @supplierCardinality 1 ..*
     * @clientRole responses
     * @directed
     */
    public List responses;
}
