/* Generated by Together */

package dig;

import java.util.*;

import owl.*;

public class SetOfEntites extends Response {
    /**
     * @link aggregationByValue
     * @associates <{owl.Entity}>
     * @associationAsClass <<set>>
     * @supplierCardinality 0..*
     * @clientRole entities
     * @directed
     */
    public Set entities;
}
