/* Generated by Together */

package owl;

public class AnnotationAssertion extends AnnotationAxiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole annotationProperty
     */
    AnnotationProperty annotationProperty;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole annotationSubject
     */
   AnnotationSubject annotationSubject;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole annotationValue
     */
   AnnotationValue annotationValue;
}