/* Generated by Together */

package owl;

public class AnnotationByURI extends Annotation {
    /**
     * @supplierCardinality 1
     * @supplierRole annotationValue
     * @directed
     */
    URI annotationValue;
}
