/* Generated by Together */

package owl;

public abstract class Annotation {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole annotationProperty
     */
    AnnotationProperty annotationProperty;
    /**
     * @directed
     * @associates <{Annotation}>
     * @supplierCardinality 0 ..*
     * @supplierRole annotationAnnotations
     */
    Set annotationAnnotations;
}
