/* Generated by Together */

package owl;

public class Annotation {
    /**
     * @supplierCardinality 1
     * @directed
     * @link aggregation
     * @clientRole annotationProperty
     */
    public AnnotationProperty annotationProperty;
}
