/* Generated by Together */

package owl;

public class AnnotationPropertyDomain extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole annotationProperty
     */
    AnnotationProperty annotationProperty;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole domain
     */
    URI domain;
}
