/* Generated by Together */

package owl;

public class AnnotationPropertyRange extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole annotationProperty
     */
    AnnotationProperty annotationProperty;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole range
     */
    URI range;
}
