/* Generated by Together */

package owl;

public class AnnotationByLiteral extends Annotation {
    /**
     * @supplierCardinality 1
     * @supplierRole annotationValue
     * @directed
     */
    Literal annotationValue;
}
