/* Generated by Together */

package owl;

public class AnonymousIndividualAnnotation extends AnnotationAxiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole anonymousIndividual
     */
    AnonymousIndividual anonymousIndividual;
    /**
     * @directed
     * @associates <{Annotation}>
     * @supplierCardinality 1 ..  *
     * @supplierRole anonymousIndividualAnnotations
     */
    Set anonymousIndividualAnnotations;
}
