/* Generated by Together */

package owl;

public class AnonymousIndividual implements Individual,AnnotationSubject,AnnotationValue  {
    /**
     * @directed
     * @supplierCardinality 1
     * @alias nodeID : String
     */
    public String nodeID;
}
