/* Generated by Together */

package owl;

public class AnonymousIndividual implements Individual {
    /**
     * @directed
     * @supplierCardinality 0..1
     * @supplierQualifier nodeID
     */
    String nodeID;
}
