/* Generated by Together */

package owl;

public class AntisymmetricObjectProperty extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty
     * @directed
     */
    /*#ObjectPropertyExpression objectProperty;*/
}
