/* Generated by Together */

package owl;

public abstract class Axiom {
    /**
     * @associates <{Annotation}>
     * @supplierCardinality *
     * @supplierRole annotations
     * @directed
     */
    public Set annotations;
}
