/* Generated by Together */

package owl;

public abstract class Axiom {
    /**
     * @directed
     * @associates <{Annotation}>
     * @supplierCardinality *
     * @supplierRole annotations
     */
    Set annotations;
}
