/* Generated by Together */

package owl;

public class ClassAssertion extends Assertion {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole classExpression
     */
    ClassExpression classExpression;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole individual
     */
    Individual individual;
}
