/* Generated by Together */

package owl;

public class ClassAssertion extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole description
     */
    Description description;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole individual
     */
    Individual individual;
}
