/* Generated by Together */

package owl;

public class Constant {
    /**
     * @link aggregation
     * @supplierCardinality 1
     * @clientQualifier value
     * @directed 
     */
    public String value;
}
