/* Generated by Together */

package owl;

import java.util.*;

public class DataOneOf extends DataRange {

    /**
     * @link aggregation
     * @associates <{Constant}>
     * @associationAsClass <<set>>
     * @supplierCardinality 1 ..*
     * @clientRole constants
     * @directed
     */
	public Set constants;
}
