/* Generated by Together */

package owl;

public class DatatypeRestriction extends DataRange {
    public String facetType;
    /**
     * @supplierCardinality 1
     * @clientRole dataRange
     * @directed
     */
    /*#DataRange dataRange;*/
    /**
     * @supplierCardinality 1
     * @clientRole restrictionValue
     * @directed
     */
    /*#Constant restrictionValue;*/
}
