/* Generated by Together */

package owl;

public class DataComplementOf extends DataRange {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole dataRange
     */
    DataRange dataRange;
}
