/* Generated by Together */

package owl;

public class DataPropertyDomain extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole dataPropertyExpression
     */
    DataPropertyExpression dataPropertyExpression;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole domain
     */
    ClassExpression domain;
}
