/* Generated by Together */

package owl;

public class DatatypeRestriction extends DataRange {
    /**
     * @supplierCardinality 1
     * @clientRole dataRange
     * @directed
     */
    /*#DataRange dataRange;*/
    /**
     * @supplierCardinality 1..*
     * @clientRole restrictions
     * @directed
     * @associationAsClass facetType
     */
    /*#Constant restrictions;*/
}
