/* Generated by Together */

package owl;

public class DataPropertyRange extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole dataPropertyExpression
     */
    DataPropertyExpression dataPropertyExpression;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole range
     */
    DataRange range;
}
