/* Generated by Together */

package owl;

public class DataPropertyDomain extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole dataProperty
     * @directed
     */
    /*#DataPropertyExpression dataProperty;*/
    /**
     * @supplierCardinality 1
     * @clientRole domain
     * @directed
     */
    /*#Description domain;*/
}
