/* Generated by Together */

package owl;

public class DataIntersectionOf extends DataRange {
    /**
     * @associates <{owl.DataRange}>
     * @supplierCardinality 2 .. *
     * @supplierRole dataRanges
     * @directed
     */
    Set dataRanges;
}

