/* Generated by Together */

package owl;

public class DataPropertyAssertion extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole dataProperty
     */
    DataPropertyExpression dataProperty;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole sourceIndividual
     */
    Individual sourceIndividual;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole targetValue
     */
    Constant targetValue;
}
