/* Generated by Together */

package owl;

public class DataHasValue extends ClassExpression {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole constant
     */
    Constant constant;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole dataPropertyExpression
     */
    DataPropertyExpression dataPropertyExpression;
}
