/* Generated by Together */

package owl;

public class DataHasValue extends Description {
    /**
     * @supplierCardinality 1
     * @clientRole constant
     * @directed
     */
    /*#Constant constant;*/
    /**
     * @supplierCardinality 1
     * @clientRole dataProperties
     * @directed
     */
    /*#DataPropertyExpression dataProperties;*/
}
