/* Generated by Together */

package owl;

public class DataSomeValuesFrom extends Description {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole dataRange
     */
    DataRange dataRange;
    /**
     * @directed
     * @associates <{DataPropertyExpression}>
     * @supplierCardinality 1 ..*
     * @supplierRole dataProperties
     * @supplierQualifier { ordered, nonunique }
     */
    public List dataProperties;
}
