/* Generated by Together */

package owl;

public class DataPropertyDomain extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole dataProperty
     */
    DataPropertyExpression dataProperty;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole domain
     */
    Description domain;
}
