/* Generated by Together */

package owl;

public class Declaration extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole entity
     * @directed
     */
    /*#OWLEntity entity;*/
}
