/* Generated by Together */

package owl;

import java.util.*;

public class DisjointUnion extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole class
     * @directed
     */
    /*#Description _class;*/
    /**
     * @link aggregation
     * @associates <{Description}>
     * @associationAsClass <<set>>
     * @supplierCardinality 2 ..*
     * @clientRole disjointClasses
     * @directed
     */
    public Set disjointClasses;
}
