/* Generated by Together */

package owl;

import java.util.*;

public class DisjointObjectProperties extends Axiom {
    /**
     * @directed
     * @associates <{ObjectPropertyExpression}>
     * @supplierCardinality 2 ..*
     * @supplierRole objectPropertyExpressions
     */
    Set objectPropertyExpressions;
}
