/* Generated by Together */

package owl;

import java.util.*;

public class DisjointDataProperties extends Axiom {

    /**
     * @link aggregation
     * @associates <{DataPropertyExpression}>
     * @associationAsClass <<set>>
     * @supplierCardinality 2 ..*
     * @clientRole dataProperties
     * @directed
     */
    public Set dataProperties;
}
