/* Generated by Together */

package owl;

public abstract class Entity {
    /**
     * @directed
     * @supplierCardinality 1
     * @alias entityURI : URI
     */
    public URI entityURI;
}


