/* Generated by Together */

package owl;

import java.util.*;

public class EquivalentObjectProperties extends Axiom {

    /**
     * @link aggregation
     * @associates <{ObjectPropertyExpression}>
     * @associationAsClass <<set>>
     * @supplierCardinality 2 ..*
     * @clientRole objectProperties
     * @directed
     */
    public Set objectProperties;
}
