/* Generated by Together */

package owl;

import java.util.*;

public class EquivalentClasses extends ClassAxiom {
    /**
     * @directed
     * @associates <{owl.ClassExpression}>
     * @supplierCardinality 2 ..*
     * @supplierRole classExpressions
     */
    Set classExpressions;
}
