/* Generated by Together */

package owl;

import java.util.*;

public class EquivalentDataProperties extends Axiom {
    /**
     * @directed
     * @associates <{DataPropertyExpression}>
     * @supplierCardinality 2 ..*
     * @supplierRole dataProperties
     */
    Set dataProperties;
}
