/* Generated by Together */

package owl;

public class FacetRestriction {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole constrainingFacet
     */
    public URI constrainingFacet;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole restrictionValue
     */
    Literal restrictionValue;
}
