/* Generated by Together */

package owl;

public class FunctionalDataProperty extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole dataProperty
     */
    DataPropertyExpression dataProperty;
}
