/* Generated by Together */

package owl;

public class FunctionalDataProperty extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole dataProperty
     * @directed
     */
    /*#DataPropertyExpression dataProperty;*/
}
