/* Generated by Together */

package owl;

public class InverseObjectProperty extends ObjectPropertyExpression {
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty
     * @directed
     */
    /*#ObjectPropertyExpression objectProperty;*/
}
