/* Generated by Together */

package owl;

public class InverseObjectProperties extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty1
     * @directed
     */
    /*#ObjectPropertyExpression objectProperty1;*/
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty2
     * @directed
     */
    /*#ObjectPropertyExpression objectProperty2;*/
}
