/* Generated by Together */

package owl;

public class InverseFunctionalObjectProperty extends ObjectPropertyAxiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole objectPropertyExpression
     */
    ObjectPropertyExpression objectPropertyExpression;
}
