/* Generated by Together */

package owl;

public class Literal implements AnnotationValue {
    /**
     * @directed
     * @supplierCardinality 1
     * @alias lexicalForm : String
     */
     public String lexicalForm;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole datatype
     */
    Datatype datatype;
}