/* Generated by Together */

package owl;

public class ObjectSomeValuesFrom extends ClassExpression {
    /**
     * @supplierCardinality 1
     * @supplierRole classExpression
     * @directed
     */
    ClassExpression classExpression;
    /**
     * @supplierCardinality 1
     * @supplierRole objectPropertyExpression
     * @directed
     */
    ObjectPropertyExpression objectPropertyExpression;
}
