/* Generated by Together */

package owl;

import java.util.*;

public class ObjectIntersectionOf extends ClassExpression {
    /**
     * @associates <{owl.ClassExpression}>
     * @supplierCardinality 2 ..*
     * @supplierRole classExpressions
     * @directed
     */
    Set classExpressions;
}
