/* Generated by Together */

package owl;

public class ObjectExactCardinality extends Description {
    int cardinality;
    /**
     * @supplierCardinality 0..1
     * @clientRole class
     * @directed
     */
    /*#Description _class;*/
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty
     * @directed
     */
    /*#ObjectPropertyExpression objectProperty;*/
}
