/* Generated by Together */

package owl;

public class ObjectMinCardinality extends Description {
    int cardinality;
    /**
     * @supplierCardinality 0..1
     * @supplierRole class
     * @directed
     */
    Description _class;
    /**
     * @supplierCardinality 1
     * @supplierRole objectProperty
     * @directed
     */
    ObjectPropertyExpression objectProperty;
}
