/* Generated by Together */

package owl;

public class ObjectPropertyDomain extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty
     * @directed
     */
    /*#ObjectPropertyExpression objectProperty;*/
    /**
     * @supplierCardinality 1
     * @clientRole domain
     * @directed
     */
    /*#Description domain;*/
}
