/* Generated by Together */

package owl;

public class ObjectUnionOf extends Description {
    /**
     * @associates <{Description}>
     * @supplierCardinality 2 .. *
     * @supplierRole classes
     * @directed
     */
    public Set classes;
}
