/* Generated by Together */

package owl;

public class ObjectPropertyDomain extends ObjectPropertyAxiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole objectPropertyExpression
     */
    ObjectPropertyExpression objectPropertyExpression;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole domain
     */
    ClassExpression domain;
}
