/* Generated by Together */

package owl;

public class ObjectHasValue extends Description {
    /**
     * @supplierCardinality 1
     * @supplierRole individual
     * @directed
     */
    Individual individual;
    /**
     * @supplierCardinality 1
     * @supplierRole objectProperty
     * @directed
     */
    ObjectPropertyExpression objectProperty;
}
