/* Generated by Together */

package owl;

public class ObjectExistsSelf extends Description {
    /**
     * @supplierCardinality 1
     * @supplierRole objectProperty
     * @directed
     */
    ObjectPropertyExpression objectProperty;
}
