/* Generated by Together */

package owl;

public class ObjectComplementOf extends Description {
    /**
     * @supplierCardinality 1
     * @clientRole class
     * @directed
     */
    /*#Description _class;*/
}
