/* Generated by Together */

package owl;

public class ObjectExactCardinality extends ClassExpression {
    /**
     * @alias cardinality : UnlimitedNatural
     */
    public int cardinality;
    /**
     * @supplierCardinality 0..1
     * @supplierRole classExpression
     * @directed
     */
    ClassExpression classExpression;
    /**
     * @supplierCardinality 1
     * @supplierRole objectPropertyExpression
     * @directed
     */
    ObjectPropertyExpression objectPropertyExpression;
}
