/* Generated by Together */

package owl;

public class ObjectPropertyAssertion extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole objectProperty
     * @directed
     */
    /*#ObjectPropertyExpression objectProperty;*/
    /**
     * @supplierCardinality 1
     * @clientRole sourceIndividual
     * @directed
     */
    /*#Individual sourceIndividual;*/
    /**
     * @supplierCardinality 1
     * @clientRole targetIndividual
     * @directed
     */
    /*#Individual targetIndividual;*/
}
