/* Generated by Together */

package owl;

public class ObjectExistsSelf extends ClassExpression {
    /**
     * @supplierCardinality 1
     * @supplierRole objectPropertyExpression
     * @directed
     */
    ObjectPropertyExpression objectPropertyExpression;
}
