/* Generated by Together */

package owl;

public abstract class OWLEntity {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole entityURI
     */
    public URI entityURI;
}


