/* Generated by Together */

package owl;

public class SubAnnotationPropertyOf extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole subAnnotationProperty
     */
    AnnotationProperty subAnnotationProperty;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole superAnnotationProperty
     */
    AnnotationProperty superAnnotationProperty;
}
