/* Generated by Together */

package owl;

public class SubClassOf extends Axiom {
    /**
     * @supplierCardinality 1
     * @clientRole subClass
     * @directed
     */
    /*#Description subClass;*/
    /**
     * @supplierCardinality 1
     * @clientRole superClass
     * @directed
     */
    /*#Description superClass;*/
}
