/* Generated by Together */

package owl;

public class SubClassOf extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole subClass
     */
    Description subClass;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole superClass
     */
    Description superClass;
}
