/* Generated by Together */

package owl;

public class SubClassOf extends ClassAxiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole subClassExpression
     */
    ClassExpression subClassExpression;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole superClassExpression
     */
    ClassExpression superClassExpression;
}
