/* Generated by Together */

package owl;

import java.util.*;

public class SubDataPropertyOf extends Axiom {
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole subDataProperty
     */
    DataPropertyExpression subDataProperty;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole superDataProperty
     */
    DataPropertyExpression superdataProperty;
}
