/* Generated by Together */

package owl;

import java.util.*;

public class SubObjectPropertyOf extends Axiom {
    /**
     * @directed
     * @associates <{ObjectPropertyExpression}>
     * @supplierCardinality 2 ..*
     * @supplierRole subObjectPropertyExpressions
     * @supplierQualifier { ordered, nonunique }
     */
    List subObjectPropertyExpressions;
    /**
     * @directed
     * @supplierCardinality 1
     * @supplierRole superObjectPropertyExpression
     */
    ObjectPropertyExpression superObjectPropertyExpression;
}
