/* Generated by Together */

package owl;

public class UntypedConstant implements Constant {
    /**
     * @supplierCardinality 0..1
     * @link aggregation
     * @directed
     * @clientQualifier languageTag*/
    private String languageTag;
}
