/* Generated by Together */

package owl;

public class UntypedConstant implements Constant {
    /**
     * @supplierCardinality 0..1
     * @directed
     * @supplierQualifier languageTag
     */
    private String languageTag;
}
